"""2022-04-23

Revision ID: 1fa00361cf63
Revises: 065987b3f5e8
Create Date: 2022-04-23 10:41:00.014314

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1fa00361cf63'
down_revision = '065987b3f5e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientredirecturilink',
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('redirect_uri_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.ForeignKeyConstraint(['redirect_uri_id'], ['redirect_uris.redirect_uri'], ),
    sa.PrimaryKeyConstraint('client_id', 'redirect_uri_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientredirecturilink')
    # ### end Alembic commands ###
