"""2022-04-23

Revision ID: 2dabf3c127c8
Revises: 1fa00361cf63
Create Date: 2022-04-23 13:52:51.696668

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2dabf3c127c8'
down_revision = '1fa00361cf63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
